### ISSUE TITLE
parsing error in servicemeshcontrolplane:   full-install

### ISSUE THREAD

**Issue by jbride** [gpe-mw-training/ocp_service_mesh_advanced#3]
Getting the following parsing error in OSSM v1.1.0 operator when attempting to instantiate a servicemeshcontrolplane:

"Reconciler error","controller":"servicemeshcontrolplane-controller","request":"admin1-istio-system/full-install","error":"Error rendering helm charts: render error in \"istio/templates/configmap.yaml\": template: istio/templates/configmap.yaml:144:30: executing \"istio/templates/configmap.yaml\" at <.Values.global.mtls.auto>: can't evaluate field auto in type interface {}","errorVerbose":"render error in \"istio/templates/configmap.yaml\": template: istio/templates/configmap.yaml:144:30: executing \"istio/templates/configmap.yaml\" at <.Values.global.mtls.auto>: can't evaluate field auto in type interface {}\nError rendering helm charts\ngithub.com/maistra/istio-operator/pkg/controller/servicemesh/controlplane.

Fix appears to be to change the *full-install* config yaml to the following:

``
global:
      disablePolicyChecks: true
      mtls:
        auto: true
        enabled: false

**Comment by jbride** [comment]
As per [this doc](https://istio.io/docs/reference/config/installation-options/#global-options), setting global.mtls.auto=true sets client side TLS configuration automatically.

I've noticed that setting this config to true introduces about 10% request failures during load testing such as the following:    

  siege -r 10 -c 10 http://user1-responder-service:8080/responders/available

Setting this to global.mtls.auto=false eliminates these failures using the same load test.

**Comment by btison** [comment]
Is that with mTLS.enabled false, and without destination rule to the target service?

**Comment by btison** [comment]
mTLS.auto set to false in control plane CR
